name: Full build and test

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 22.x, 24.x ]
        os: [ ubuntu-latest, ubuntu-24.04-arm ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Prepare Ubuntu
        run: |
          sudo apt-get install -y can-utils
          sudo apt-get install -y libnode-dev
          sudo apt-get install linux-modules-extra-$(uname -r)

      - name: Prepare deps
        run: |
          npm ci

      - name: Compile
        run: |
          npm run configure
          npm run build:all

      - name: Lint
        run: |
          npm run lint

      - name: Perform tests
        run: |
          sh prepare_test_env.sh
          npm run test
