name: Publish on NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Prepare Ubuntu
        run: |
          sudo apt-get install -y can-utils
          sudo apt-get install -y libnode-dev
          sudo apt-get install linux-modules-extra-$(uname -r)

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run configure
          npm run build:all

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          sh prepare_test_env.sh
          npm test

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
