name: Publish on NPM

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Prepare Ubuntu
        run: |
          sudo apt-get install -y can-utils
          sudo apt-get install -y libsocketcan-dev
          sudo apt-get install -y libnode-dev
          sudo apt-get install linux-modules-extra-$(uname -r)

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm run configure
          pnpm run build:all

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: |
          sh prepare_test_env.sh
          pnpm test

      - name: Publish
        run: npm publish
