name: Publish on NPM

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.22.2
          registry-url: 'https://registry.npmjs.org'

      - name: Prepare Ubuntu
        run: |
          sudo apt-get install -y can-utils
          sudo apt-get install -y libnode-dev
          sudo apt-get install linux-modules-extra-$(uname -r)

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm run configure
          pnpm run build:all

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: |
          sh prepare_test_env.sh
          pnpm test

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
